//#pragma use_dxc

#pragma kernel ExternalForces
#pragma kernel InitializeSpacialPartitionBuffers
#pragma kernel CalculateDensities
#pragma kernel CalculatePressureForce
#pragma kernel CalculateViscosity
#pragma kernel UpdatePositions
#pragma kernel CopyBuffer
#pragma kernel InitOffsets
#pragma kernel CalcOffsets
#pragma kernel Debug

#define NUM_THREADS							64
#define NEIGHBOR_SEARCH_NUM_THREADS			64

//Neighbor search defines
//The max number of threads that will coordinate to calculate values for a given origin cell
//A value of 1 should yield identical behavior to the naiive implementation, since there's no coordination
//Any value over 27 would be meaningless because you'd be computing more neighbors than exist simultanously
#define NS_MAX_COORD_BLOCK_SIZE				3		
#define NS_USE_REGISTER_CACHE_POS			1
#define NS_USE_REGISTER_CACHE_SUMS			1

//All of these diagnostic or debug should be commented out in prod
#define NS_DEBUG_ASSISTANCE							//Generally makes debugging easier by doing things like strictly unnecessary cleanup of values
//#define NS_ADDITIONAL_COORDINATOR_CONTEXT			//Adds more data that rides with NSCoordBlock which can help with debugging, but increases register pressure

// Includes
#include "./FluidMaths3D.hlsl"
#include "./SpatialHash3D.hlsl"

// Buffers
RWStructuredBuffer<float3> Positions;
RWStructuredBuffer<float3> PredictedPositions;
RWStructuredBuffer<float3> Velocities;
RWStructuredBuffer<float2> Densities; // Density, Near Density

RWStructuredBuffer<float3> DebugValues;

//Multipurpose spacial partitioning array, to be initialized here but used by sort
RWStructuredBuffer<uint> spacialPart1;	//Initialized to keys. Remains keys for reindexing.
RWStructuredBuffer<uint> spacialPart2;	//Initialized to indices. Used as indices for reindexing, but afterwards set to offsets.
RWStructuredBuffer<float3> tempBuffer;	// Used to copy values for memory coalescing

// Settings
const uint numParticles;

const float gravity;
const float deltaTime;
const float collisionDamping;
const float smoothingRadius;
const float targetDensity;
const float pressureMultiplier;
const float nearPressureMultiplier;
const float viscosityStrength;
const float edgeForce;
const float edgeForceDst;
const float3 boundsSize;
const float3 centre;
const int copyBufferId;			//Position = 0, PredictedPosition = 1, Velocity = 2, Density = 3
const int copyDirection;		//0 = real buffer to temp buffer, 1 = temp buffer to real buffer

const float4x4 localToWorld;
const float4x4 worldToLocal;

const float2 interactionInputPoint;
const float interactionInputStrength;
const float interactionInputRadius;

float PressureFromDensity(float density)
{
	return (density - targetDensity) * pressureMultiplier;
}

float NearPressureFromDensity(float nearDensity)
{
	return nearDensity * nearPressureMultiplier;
}

void ResolveCollisions(uint particleIndex)
{
	// Transform position/velocity to the local space of the bounding box (scale not included)
	float3 posLocal = mul(worldToLocal, float4(Positions[particleIndex], 1)).xyz;
	float3 velocityLocal = mul(worldToLocal, float4(Velocities[particleIndex], 0)).xyz;

	// Calculate distance from box on each axis (negative values are inside box)
	const float3 halfSize = 0.5;
	const float3 edgeDst = halfSize - abs(posLocal);

	// Resolve collisions
	if (edgeDst.x <= 0)
	{
		posLocal.x = halfSize.x * sign(posLocal.x);
		velocityLocal.x *= -1 * collisionDamping;
	}
	if (edgeDst.y <= 0)
	{
		posLocal.y = halfSize.y * sign(posLocal.y);
		velocityLocal.y *= -1 * collisionDamping;
	}
	if (edgeDst.z <= 0)
	{
		posLocal.z = halfSize.z * sign(posLocal.z);
		velocityLocal.z *= -1 * collisionDamping;
	}

	// Transform resolved position/velocity back to world space
	Positions[particleIndex] = mul(localToWorld, float4(posLocal, 1)).xyz;
	Velocities[particleIndex] = mul(localToWorld, float4(velocityLocal, 0)).xyz;

}

[numthreads(NUM_THREADS,1,1)]
void ExternalForces (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	// External forces (gravity)
	Velocities[id.x] += float3(0, gravity, 0) * deltaTime;

	// Predict
	PredictedPositions[id.x] = Positions[id.x] + Velocities[id.x] * 1 / 120.0;
}

[numthreads(NUM_THREADS,1,1)]
void InitializeSpacialPartitionBuffers (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	uint index = id.x;

	// Update index buffer
	int3 cell = GetCell3D(PredictedPositions[index], smoothingRadius);
	uint hash = HashCell3D(cell);
	uint key = KeyFromHash(hash, numParticles);

	spacialPart1[index] = key;
	spacialPart2[index] = index;
}

[numthreads(NUM_THREADS,1,1)]
void CalculateDensities (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;
	float density = 0;
	float nearDensity = 0;

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;
			
			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate density and near density
			float dst = sqrt(sqrDstToNeighbour);
			density += DensityKernel(dst, smoothingRadius);
			nearDensity += NearDensityKernel(dst, smoothingRadius);
		}
	}
	
	Densities[id.x] = float2(density, nearDensity);
}

[numthreads(NUM_THREADS,1,1)]
void CalculatePressureForce (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	// Calculate pressure
	float density = Densities[id.x][0];
	float densityNear = Densities[id.x][1];
	float pressure = PressureFromDensity(density);
	float nearPressure = NearPressureFromDensity(densityNear);
	float3 pressureForce = 0;
	
	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;

			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;
			// Skip if looking at self
			if (unincIndex == id.x) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate pressure force
			float densityNeighbour = Densities[unincIndex][0];
			float nearDensityNeighbour = Densities[unincIndex][1];
			float neighbourPressure = PressureFromDensity(densityNeighbour);
			float neighbourPressureNear = NearPressureFromDensity(nearDensityNeighbour);

			float sharedPressure = (pressure + neighbourPressure) / 2;
			float sharedNearPressure = (nearPressure + neighbourPressureNear) / 2;

			float dst = sqrt(sqrDstToNeighbour);
			float3 dir = dst > 0 ? offsetToNeighbour / dst : float3(0, 1, 0);

			pressureForce += dir * DensityDerivative(dst, smoothingRadius) * sharedPressure / densityNeighbour;
			pressureForce += dir * NearDensityDerivative(dst, smoothingRadius) * sharedNearPressure / nearDensityNeighbour;
		}
	}

	float3 acceleration = pressureForce / density;
	Velocities[id.x] += acceleration * deltaTime;
}


[numthreads(NUM_THREADS,1,1)]
void CalculateViscosity (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;
		
	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;

	float3 viscosityForce = 0;
	float3 velocity = Velocities[id.x];

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;			
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;

			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;
			// Skip if looking at self
			if (unincIndex == id.x) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate viscosity
			float dst = sqrt(sqrDstToNeighbour);
			float3 neighbourVelocity = Velocities[unincIndex];
			viscosityForce += (neighbourVelocity - velocity) * SmoothingKernelPoly6(dst, smoothingRadius);
		}
	}
	Velocities[id.x] += viscosityForce * viscosityStrength * deltaTime;
}

[numthreads(NUM_THREADS, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	Positions[id.x] += Velocities[id.x] * deltaTime;
	ResolveCollisions(id.x);
}

// The branchiness of this kernel is okay because all threads will follow the same branches on a given Dispatch so there will be no divergence
[numthreads(NUM_THREADS, 1, 1)]
void CopyBuffer(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	if (copyDirection == 0)
	{
		// Copy to temp buffer
		uint uncoalescedIndex = spacialPart2[id.x];
		if (copyBufferId == 0)
		{
			tempBuffer[id.x] = Positions[uncoalescedIndex];
		} 
		else if (copyBufferId == 1)
		{
			tempBuffer[id.x] = PredictedPositions[uncoalescedIndex];
		}
		else if (copyBufferId == 2)
		{
			tempBuffer[id.x] = Velocities[uncoalescedIndex];
		}
		else if (copyBufferId == 3)
		{
			float2 density = Densities[uncoalescedIndex];
			tempBuffer[id.x] = float3(density[0], density[1], 0.0);
		}
	}
	else
	{
		// Copy from temp buffer
		if (copyBufferId == 0)
		{
			Positions[id.x] = tempBuffer[id.x];
		} 
		else if (copyBufferId == 1)
		{
			PredictedPositions[id.x] = tempBuffer[id.x];
		}
		else if (copyBufferId == 2)
		{
			Velocities[id.x] = tempBuffer[id.x];
		}
		else if (copyBufferId == 3)
		{
			float3 density = tempBuffer[id.x];
			Densities[id.x] = float2(density[0], density[1]);
		}
	}
}

// Reinitialized the array formerly used to store scatter indices for sorting to be the key offset array.
// The values are all numParticles (which is 1 more than the maximum possible key) in order to ensure that
// any possible key is less than this value. This is important for determing the end of the key bucket
[numthreads(NUM_THREADS, 1, 1)]
void InitOffsets(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) { return; }

	spacialPart2[id.x] = numParticles;
}

// Calculate offsets into the sorted spacialPart1 buffer (used for spatial hashing).
// For example, given an spacialPart1 buffer sorted by key like so: {2, 2, 2, 3, 6, 6, 9, 9, 9, 9}
// The resulting Offsets (spacialPart2) calculated here should be:  {-, -, 0, 3, -, -, 4, -, -, 6}
// (where '-' represents elements that won't be read/written)
// 
// Usage example:
// Say we have a particular particle P, and we want to know which particles are in the same grid cell as it.
// First we would calculate the Key of P based on its position. Let's say in this example that Key = 9.
// Next we can look up spacialPart2[Key] to get: spacialPart2[9] = 6
// This tells us that SortedEntries[6] is the first particle that's in the same cell as P.
// We can then loop until we reach a particle with a different cell key in order to iterate over all the particles in the cell.
// 
// NOTE: offsets buffer must filled with values equal to (or greater than) its length to ensure that this works correctly
// So this depends on InitOffsets being run.
[numthreads(NUM_THREADS, 1, 1)]
void CalcOffsets(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) { return; }

	uint i = id.x;

	uint key = spacialPart1[i];
	uint keyPrev = i == 0 ? numParticles : spacialPart1[i - 1];

	if (key != keyPrev)
	{
		spacialPart2[key] = i;
	}
	
}


//TODO Test Failures: NS_MAX_COORD_BLOCK_SIZE = 8 yields inconsistent (not every frame) small clusters of failures.
//I suspect hash conflicts related based on location they occur in.
struct NSCoordBlock
{
	uint globalId;
	uint threadBlockId;
	uint id;								//id within the coord block
	uint coordBlock;						//Index of coord block working on this hash
	uint size;
};

struct NSSearchTargetBlock
{
	uint startIndex;						//Thread block id of start index of coordinator block to search
	uint size;					//Coordinator block size
	int3 originCell;
};

struct NSSearchIteration
{
	uint count;								//Global number of iterations computed across all neighbors across all blocks. 
	uint neighborIndex;						//The neighbor index in Offsets3D to search this iteration
};

struct NSSharedMemCache
{
	//Data present in shared memory but being cached in registers for fast and frequent access
	float3 positions[NS_MAX_COORD_BLOCK_SIZE];
	float3 partialSums[NS_MAX_COORD_BLOCK_SIZE];
};

struct NeighborSearchData
{
	NSCoordBlock coordBlock;
	NSSearchTargetBlock searchTarget;
	NSSearchIteration iteration;
	NSSharedMemCache cache;
};

//Fundamental values used for neighbor calculations
groupshared float3 sh_positions[NEIGHBOR_SEARCH_NUM_THREADS];
groupshared float3 sh_dependentValues[NEIGHBOR_SEARCH_NUM_THREADS];
groupshared float3 sh_partialSums[NEIGHBOR_SEARCH_NUM_THREADS];

//Used for inter-block coordination
groupshared uint sh_blockSizes[NEIGHBOR_SEARCH_NUM_THREADS];
groupshared int sh_neighborIndex[NEIGHBOR_SEARCH_NUM_THREADS];

NeighborSearchData performNeighborSearch(NeighborSearchData ns)
{
	float3 pos;
	int3 originCell = ns.searchTarget.originCell;
	float sqrRadius = smoothingRadius * smoothingRadius;
	float density = 0;
	float nearDensity = 0;

	uint thisCoordBlockStartIndex = ns.coordBlock.threadBlockId - ns.coordBlock.id;
	uint completionIteration = ceil(27.0 / ns.coordBlock.size);
	bool completed = false;

	// Neighbour search
	for (int globalIteration = 0; globalIteration < 27; globalIteration++)
	{
		uint hash = HashCell3D(originCell + offsets3D[ns.iteration.neighborIndex]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		//TODO testing purposes only. Remove second condition
		if ((ns.iteration.neighborIndex < 27) && (ns.searchTarget.startIndex == thisCoordBlockStartIndex))
		{
			while (currIndex < numParticles)
			{
				unincIndex = currIndex;
				currIndex++;

				neighborKey = spacialPart1[unincIndex];
				// Exit if no longer looking at correct bin
				if (neighborKey != key) break;

				float3 neighbourPos = PredictedPositions[unincIndex];
				neighborCell = GetCell3D(neighbourPos, smoothingRadius);
				neighborHash = HashCell3D(neighborCell);

				// Skip if hash does not match
				if (neighborHash != hash) continue;

				for (uint curCoordBlockIndex = 0; curCoordBlockIndex < NS_MAX_COORD_BLOCK_SIZE; curCoordBlockIndex++)
				{
					if (curCoordBlockIndex >= ns.coordBlock.size) break;

					pos = ns.cache.positions[curCoordBlockIndex];
					float3 offsetToNeighbour = neighbourPos - pos;
					float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

					// Skip if not within radius
					float insideRadius = (sqrDstToNeighbour <= sqrRadius);

					if (insideRadius)
					{
						// Calculate density and near density
						float dst = sqrt(sqrDstToNeighbour);
						//Don't question the multiplication by 1...It appears to be a bug with compiler optimization
						ns.cache.partialSums[curCoordBlockIndex][0] += insideRadius * DensityKernel(dst, smoothingRadius);
						ns.cache.partialSums[curCoordBlockIndex][1] += insideRadius * NearDensityKernel(dst, smoothingRadius);
					}
				}
			}
		}

		ns.iteration.count++;
		uint sharedNeighborIndex = sh_neighborIndex[ns.coordBlock.threadBlockId];

		for (int i = 0; i < NS_MAX_COORD_BLOCK_SIZE; i++)
		{
			if (completionIteration == ns.iteration.count)
			{
				uint nonConflictIndex = (ns.coordBlock.id + i) % NS_MAX_COORD_BLOCK_SIZE;
				uint sharedMemIndex = ns.searchTarget.startIndex + nonConflictIndex;
				float3 value = ns.cache.partialSums[nonConflictIndex];
				if (nonConflictIndex < ns.coordBlock.size)
				{
					value += sh_partialSums[sharedMemIndex];
				}
				GroupMemoryBarrierWithGroupSync();

				if (nonConflictIndex < ns.coordBlock.size)
				{
					sh_partialSums[sharedMemIndex] = value;
					if (ns.coordBlock.id == 0)
					{
						sh_neighborIndex[sharedMemIndex] = -1;
					}
				}
				GroupMemoryBarrierWithGroupSync();
			}
			else
			{
				GroupMemoryBarrierWithGroupSync();
				GroupMemoryBarrierWithGroupSync();
			}
		}

		if (completionIteration == ns.iteration.count)
		{
			uint neighboringCoordBlockEndIndex = (ns.searchTarget.startIndex - 1) % NEIGHBOR_SEARCH_NUM_THREADS;
			uint neighboringCoordBlockSize = sh_blockSizes[neighboringCoordBlockEndIndex];
			uint neighboringCoordBlockStartIndex = neighboringCoordBlockEndIndex - neighboringCoordBlockSize - 1;
			uint neighboringCoordBlockLatestNeighborIndex = sh_neighborIndex[neighboringCoordBlockEndIndex];
			uint neighboringCoordBlockHasFinished = (neighboringCoordBlockLatestNeighborIndex == -1) || (neighboringCoordBlockLatestNeighborIndex >= 27 - 1);

			completed = neighboringCoordBlockHasFinished;
			if (!neighboringCoordBlockHasFinished)
			{
				NSSearchTargetBlock newSearchTarget;
				newSearchTarget.startIndex = neighboringCoordBlockStartIndex;
				newSearchTarget.size = neighboringCoordBlockSize;
				float3 firstParticlePosition = sh_positions[neighboringCoordBlockStartIndex];
				newSearchTarget.originCell = GetCell3D(firstParticlePosition, smoothingRadius);

				ns.searchTarget = newSearchTarget;

				uint iterationsLeft = ceil((27.0 - neighboringCoordBlockLatestNeighborIndex) / (ns.searchTarget.size + ns.coordBlock.size));
				completionIteration = ns.iteration.count + iterationsLeft;
			}
		}

		if (ns.searchTarget.startIndex != thisCoordBlockStartIndex)
		{
			if (ns.coordBlock.id < ns.searchTarget.size)
			{
				uint allThreadsHelped = floor(ns.searchTarget.size / ns.coordBlock.size);
				uint remainder = ns.coordBlock.size - allThreadsHelped * ns.searchTarget.size;

				sh_neighborIndex[ns.searchTarget.startIndex + ns.coordBlock.id] += allThreadsHelped + (ns.coordBlock.id < remainder);
			}
		}
		GroupMemoryBarrierWithGroupSync();

		if (!completed)
		{
			uint indicesToSkipDueToHelpFromOtherBlocks = sharedNeighborIndex - ns.iteration.neighborIndex;
			ns.iteration.neighborIndex += ns.coordBlock.size + indicesToSkipDueToHelpFromOtherBlocks;
			sh_neighborIndex[ns.coordBlock.threadBlockId] = ns.iteration.neighborIndex;
		}
	}

	ns.cache.partialSums[ns.coordBlock.id] = sh_partialSums[ns.coordBlock.threadBlockId];

	return ns;
}

NeighborSearchData initNeighborSearch(uint globalId, uint threadBlockId)
{
	//Global end of data init (assume numParticles check at end that prevents write, so fake values here are fine)
	float3 pos = float3(-9999, -9999, -9999);
	float3 dependentValue = float3(-9999, -9999, -9999);
	float3 partialSum = float3(0, 0, 0);

	//If not end of global data, read global value
	if (globalId < numParticles)
	{
		pos = PredictedPositions[globalId];
		//TODO init dependent values somehow
	}

	sh_positions[threadBlockId] = pos;
	sh_dependentValues[threadBlockId] = dependentValue;
	sh_partialSums[threadBlockId] = partialSum;

	GroupMemoryBarrierWithGroupSync();										//Sync 1

	//Initialize Coordinator Data
	NSCoordBlock coordBlock;
	NSSearchTargetBlock searchTarget;

	int3 originCell = GetCell3D(pos, smoothingRadius);
	uint originHash = HashCell3D(originCell);

	coordBlock.globalId = globalId;
	coordBlock.threadBlockId = threadBlockId;
	searchTarget.originCell = originCell;

	//Crawl to the left in shared memory to find the beginning of the hash (not key, coordinators operate at hash-level)
	//Also fills positions array with up to first NS_MAX_COORD_BLOCK_SIZE elements to the left of current thread
	float3 positions[NS_MAX_COORD_BLOCK_SIZE];
	positions[0] = pos;
	uint numHashMatchesFound = 0;
	bool hashEndFound = false;

	float3 curPosition;
	int3 curOrigin;
	uint curOriginHash;

	for (int backSearchIndex = threadBlockId - 1;
		(backSearchIndex >= 0) && !hashEndFound;
			backSearchIndex--)
	{
		curPosition = sh_positions[backSearchIndex];
		curOrigin = GetCell3D(curPosition, smoothingRadius);
		curOriginHash = HashCell3D(curOrigin);

		hashEndFound = curOriginHash != originHash;

		numHashMatchesFound += !hashEndFound;

		if ((!hashEndFound) && (numHashMatchesFound < NS_MAX_COORD_BLOCK_SIZE))
		{
			positions[numHashMatchesFound] = curPosition;
		}
	}

	uint hashStartIndex = threadBlockId - numHashMatchesFound;
	uint coordBlocksBeforeThis = floor((float)numHashMatchesFound / NS_MAX_COORD_BLOCK_SIZE);
	uint coordBlockStartIndex = hashStartIndex + coordBlocksBeforeThis * NS_MAX_COORD_BLOCK_SIZE;
	uint id = threadBlockId - coordBlockStartIndex;

	searchTarget.startIndex = coordBlockStartIndex;

	coordBlock.coordBlock = coordBlocksBeforeThis;
	coordBlock.id = id;

	//We could have added values to positions array that are outside coord block bounds. We need to trim this down.
	//So we will consider coordBlock.id + 1 as the current size of the positions array.
	uint size = (coordBlock.id + 1);

	//Reverse the array to ensure it aligns with the order in shared memory
	for (int swapIndex = 0; swapIndex < floor(size / 2.0); swapIndex++)
	{
		uint leftIndex = swapIndex;
		uint rightIndex = (size - 1) - swapIndex;

		float3 tmp = positions[leftIndex];
		positions[leftIndex] = positions[rightIndex];
		positions[rightIndex] = tmp;
	}

	//Crawl to the right in shared memory to find the end of the hash (not key, coordinators operate at hash-level)
	//Also fills positions array with up to NS_MAX_COORD_BLOCK_SIZE total elements to the right of current thread
	//Stops at the end of the coord block, as any further positions will be managed by the next coord block
	hashEndFound = false;

	for (int forwardSearchIndex = threadBlockId + 1;
		(forwardSearchIndex < NEIGHBOR_SEARCH_NUM_THREADS) && !hashEndFound && (size < NS_MAX_COORD_BLOCK_SIZE); 
			forwardSearchIndex++)
	{
		curPosition = sh_positions[forwardSearchIndex];
		curOrigin = GetCell3D(curPosition, smoothingRadius);
		curOriginHash = HashCell3D(curOrigin);

		hashEndFound = curOriginHash != originHash;

		if (!hashEndFound)
		{
			positions[size] = curPosition;
			size++;
		}
	}

	coordBlock.size = size;
	searchTarget.size = size;
	sh_blockSizes[threadBlockId] = size;

	//This isn't strictly necessary, but it's possible that there are values in positions array that don't belong in the block
//If consumers use size correctly, these fake values will never be used. But I want to reset them anyway because it bothers me
//So for the sake of perf, I surround in a compiler directive
#ifdef NS_DEBUG_ASSISTANCE
	for (int clearIndex = size; clearIndex < NS_MAX_COORD_BLOCK_SIZE; clearIndex++)
	{
		positions[clearIndex] = float3(0, 0, 0);
	}
#endif


	NSSharedMemCache cache;
	[unroll]
	for (int cacheIndex = 0; cacheIndex < NS_MAX_COORD_BLOCK_SIZE; cacheIndex++)
	{
		cache.positions[cacheIndex] = positions[cacheIndex];
		cache.partialSums[cacheIndex] = float3(0, 0, 0);
	}

	NSSearchIteration iteration;
	iteration.count = 0;
	iteration.neighborIndex = coordBlock.id;
	sh_neighborIndex[threadBlockId] = coordBlock.id;

	NeighborSearchData searchData;
	searchData.coordBlock = coordBlock;
	searchData.searchTarget = searchTarget;
	searchData.iteration = iteration;
	searchData.cache = cache;

	return searchData;
}

void TestInitNeighborSearch(uint3 globalId, uint3 warpId)
{
	//For increased validation, enable NS_ADDITIONAL_COORDINATOR_CONTEXT

	//Init Values
	uint index = warpId.x;
	uint indexOffset = (warpId.x == 0) ? -1 * (NEIGHBOR_SEARCH_NUM_THREADS - 1) : 1;
	uint prevIndex = index - indexOffset;
	uint globalIndex = globalId.x;
	uint globalOffset = (globalId.x == 0) ? -1 * (numParticles - NEIGHBOR_SEARCH_NUM_THREADS - 1) : 0;
	uint globalWarpOffset = (warpId.x == 0) ? -1 * (NEIGHBOR_SEARCH_NUM_THREADS - 1) : 1;
	uint prevGlobalIndex = globalIndex - globalOffset - globalWarpOffset;

	NeighborSearchData prevData = initNeighborSearch(prevGlobalIndex, prevIndex);
	GroupMemoryBarrierWithGroupSync();
	NeighborSearchData xData = initNeighborSearch(globalIndex, index);
	GroupMemoryBarrierWithGroupSync();

	float3 xPos = sh_positions[index];
	float3 pPos = sh_positions[prevIndex];

	int3 xOrigin = GetCell3D(xPos, smoothingRadius);
	int3 pOrigin = GetCell3D(pPos, smoothingRadius);

	uint xOriginHash = HashCell3D(xOrigin);
	uint pOriginHash = HashCell3D(pOrigin);

	uint xOriginKey = KeyFromHash(xOriginHash, numParticles);
	uint pOriginKey = KeyFromHash(pOriginHash, numParticles);

	bool sameOriginHash = (pOriginHash == xOriginHash);

	//Checks for metadata

	bool isIntraBlock = false;
	bool isInterBlock = false;
	bool isDifferentHash = false;

	bool coordBlockBoundary = false;
	bool startsMismatch = false;
	bool hashMismatch = false;
	bool intraCoordBlockMismatch = false;
	bool sizeMismatch = false;
	bool idsNonsequential = false;

	bool interCoordBlockNonsequential = false;
	bool invalididEnd = false;
	bool invalididStart = false;
	bool blockEndNotFullSize = false;
	bool blockStartsNonStridedBySize = false;

	bool newHashStartIndexNonSelf = false;
	bool newHashCoordBlockNonZero = false;
	bool newHashidNonZero = false;

	if (sameOriginHash)
	{
		//The beginning of the thread block deserves special consideration
		if (warpId.x == 0)
		{
			isInterBlock = true;

			invalididStart = xData.coordBlock.id != 0;
			interCoordBlockNonsequential = xData.coordBlock.coordBlock != 0;
			blockStartsNonStridedBySize = xData.searchTarget.startIndex != 0;
		}
		else
		{
			hashMismatch = HashCell3D(prevData.searchTarget.originCell) != HashCell3D(xData.searchTarget.originCell);

			coordBlockBoundary = (prevData.coordBlock.id == NS_MAX_COORD_BLOCK_SIZE - 1) && (xData.coordBlock.id == 0);
			if (!coordBlockBoundary)
			{
				isIntraBlock = true;

				//cur and previous should coordinate with each other
				sizeMismatch = (prevData.coordBlock.size != xData.coordBlock.size);
				idsNonsequential = prevData.coordBlock.id != xData.coordBlock.id - 1;
				intraCoordBlockMismatch = prevData.coordBlock.coordBlock != xData.coordBlock.coordBlock;
				startsMismatch = prevData.searchTarget.startIndex != xData.searchTarget.startIndex;
			}
			else
			{
				isInterBlock = true;

				invalididEnd = prevData.coordBlock.id != NS_MAX_COORD_BLOCK_SIZE - 1;
				invalididStart = xData.coordBlock.id != 0;
				blockEndNotFullSize = prevData.coordBlock.size != NS_MAX_COORD_BLOCK_SIZE;
				interCoordBlockNonsequential = prevData.coordBlock.coordBlock != xData.coordBlock.coordBlock - 1;
				blockStartsNonStridedBySize = prevData.searchTarget.startIndex + NS_MAX_COORD_BLOCK_SIZE != xData.searchTarget.startIndex;
			}
		}
	}
	else
	{
		//If different origins (either in the case of a hash conflict or legitimately different origins), then there's no
		//relationship between the previous and this coordinator blocks. So just test that this coordinator block starts a new
		//set of coordinator blocks
		bool isDifferentHash = true;

		newHashidNonZero = xData.coordBlock.id != 0;
		newHashCoordBlockNonZero = xData.coordBlock.coordBlock != 0;
		newHashStartIndexNonSelf = xData.searchTarget.startIndex != index;
	}

	bool globalIdsNonsequential = (prevData.coordBlock.globalId != xData.coordBlock.globalId - 1) && (xData.coordBlock.threadBlockId != 0) && (xData.coordBlock.globalId != 0);
	bool threadBlockIdsNonsequential = (prevData.coordBlock.threadBlockId != xData.coordBlock.threadBlockId - 1) && (xData.coordBlock.threadBlockId != 0);
	bool searchTargetBlockSizeMismatch = (xData.searchTarget.size != xData.coordBlock.size);
	bool iterationCountNonZero = xData.iteration.count != 0;
	bool iterationNeighborIndexIncorrect = xData.iteration.neighborIndex != xData.coordBlock.id;

	bool unconditionalTestsFailed = globalIdsNonsequential || threadBlockIdsNonsequential || searchTargetBlockSizeMismatch || iterationCountNonZero || iterationNeighborIndexIncorrect;
	bool intraCoordBlockTestsFailed = startsMismatch || hashMismatch || intraCoordBlockMismatch || sizeMismatch || idsNonsequential;
	bool interCoordBlockTestsFailed = interCoordBlockNonsequential || hashMismatch || invalididEnd || invalididStart || blockEndNotFullSize || blockStartsNonStridedBySize;
	bool newHashTestsFailed = newHashStartIndexNonSelf || newHashCoordBlockNonZero || newHashidNonZero;

	bool metadataValueFailures = unconditionalTestsFailed || intraCoordBlockTestsFailed || interCoordBlockTestsFailed || newHashTestsFailed;

	// Array value validation

	bool positionValueFailures = false;
	bool partialSumValueFailures = false;
	bool dependentValueFailures = false;

	//Only check values if the metadata is good, otherwise could cause arrayindexoutofbounds
	if (!metadataValueFailures)
	{
		//Checks for Position Values
		uint threadBlockStartIndex = globalIndex - index;
		uint coordBlockStartIndexInThreadBlock = index - xData.coordBlock.id;
		uint coordBlockGlobalStartIndex = threadBlockStartIndex + coordBlockStartIndexInThreadBlock;

		for (uint i = 0; i < xData.coordBlock.size; i++)
		{
			float3 curBuffPos = PredictedPositions[coordBlockGlobalStartIndex + i];
			float3 curResultPos = xData.cache.positions[i];

			positionValueFailures = positionValueFailures || ((curResultPos.x != curBuffPos.x) || 
				(curResultPos.y != curBuffPos.y) || (curResultPos.z != curBuffPos.z) );

			float3 curResultSums = xData.cache.partialSums[i];

			partialSumValueFailures = partialSumValueFailures || ((curResultSums.x != 0) ||
				(curResultSums.y != 0) || (curResultSums.z != 0));

			//TODO validate dependent values
		}
	}

	bool arrayValueFailures = positionValueFailures || partialSumValueFailures || dependentValueFailures;

	//Validate shared memory values

	float3 pGlobMem = PredictedPositions[globalIndex];
	float3 pSharedMem = sh_positions[index]; 
	float3 pPartSumsSharedMem = sh_partialSums[index];

	bool sh_positionsIncorrect = (pSharedMem.x != pGlobMem.x) || (pSharedMem.y != pGlobMem.y) || (pSharedMem.z != pGlobMem.z);
	//TODO bool sh_dependentValuesIncorrect = sh_dependentValues != ???
	bool sh_partialSumsIncorrect = (pPartSumsSharedMem.x != 0) || (pPartSumsSharedMem.y != 0) || (pPartSumsSharedMem.z != 0);
	bool sh_blockSizesIncorrect = sh_blockSizes[index] != xData.coordBlock.size;
	bool sh_neighborIndexIncorrect = sh_neighborIndex[index] != (int)xData.coordBlock.id;

	bool anySharedMemValueIncorrect = sh_positionsIncorrect || sh_partialSumsIncorrect || sh_blockSizesIncorrect || sh_neighborIndexIncorrect;

	bool someFailures = metadataValueFailures || arrayValueFailures || anySharedMemValueIncorrect;

	float testResultFloat = (someFailures);
	DebugValues[globalId.x] = float3(testResultFloat, testResultFloat, testResultFloat);
}

float2 CalculateDensitiesExperimental(uint3 id)
{
	if (id.x >= numParticles) return float2(-1, -1);

	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;
	float density = 0;
	float nearDensity = 0;

	// Neighbour search
	for (int i = 0; i < 27; i++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		uint curIndex = spacialPart2[key];

		while (curIndex < numParticles)
		{
			//Modulo is surprisingly expensive, so looking up the key from global memory in parallel is cheaper, apparently
			uint neighborKey = spacialPart1[curIndex];
			float3 neighbourPos = PredictedPositions[curIndex];

			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;

			int3 neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			uint neighborHash = HashCell3D(neighborCell);

			bool hashMatches = (neighborHash == hash);

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			bool withinRadius = (sqrDstToNeighbour <= sqrRadius);

			float dst = sqrt(sqrDstToNeighbour);
			density += hashMatches * withinRadius * DensityKernel(dst, smoothingRadius);
			nearDensity += hashMatches * withinRadius * NearDensityKernel(dst, smoothingRadius);

			curIndex++;
		}
	}

	return float2(density, nearDensity);
}

[numthreads(NEIGHBOR_SEARCH_NUM_THREADS, 1, 1)]
void Debug(uint3 globalId : SV_DispatchThreadID, uint3 threadBlockId : SV_GroupThreadID)
{
	if (globalId.x >= numParticles) return;

	float2 actualResult = CalculateDensitiesExperimental(globalId);
	float2 expectedResult = Densities[globalId.x];

	const float floatingPointPrecisionErrorAvoidanceThreshold = 0.0;
	bool failed = (abs(actualResult.x - expectedResult.x) > floatingPointPrecisionErrorAvoidanceThreshold) 
		|| (abs(actualResult.y - expectedResult.y) > floatingPointPrecisionErrorAvoidanceThreshold);

	float testResultFloat = failed;
	DebugValues[globalId.x] = float3(testResultFloat, testResultFloat, testResultFloat);
	//Densities[globalId.x] = actualResult;
}