#pragma kernel ExternalForces
#pragma kernel InitializeSpacialPartitionBuffers
#pragma kernel CalculateDensities
#pragma kernel CalculatePressureForce
#pragma kernel CalculateViscosity
#pragma kernel UpdatePositions
#pragma kernel CopyBuffer
#pragma kernel InitOffsets
#pragma kernel CalcOffsets
#pragma kernel Debug

#define NUM_THREADS							64
#define NEIGHBOR_SEARCH_NUM_THREADS			32

//Neighbor search defines
#define SHARED_MEM_BANKS					32

// Includes
#include "./FluidMaths3D.hlsl"
#include "./SpatialHash3D.hlsl"

// Buffers
RWStructuredBuffer<float3> Positions;
RWStructuredBuffer<float3> PredictedPositions;
RWStructuredBuffer<float3> Velocities;
RWStructuredBuffer<float2> Densities; // Density, Near Density

RWStructuredBuffer<float3> DebugValues;

//Multipurpose spacial partitioning array, to be initialized here but used by sort
RWStructuredBuffer<uint> spacialPart1;	//Initialized to keys. Remains keys for reindexing.
RWStructuredBuffer<uint> spacialPart2;	//Initialized to indices. Used as indices for reindexing, but afterwards set to offsets.
RWStructuredBuffer<float3> tempBuffer;	// Used to copy values for memory coalescing

// Settings
const uint numParticles;
const float gravity;
const float deltaTime;
const float collisionDamping;
const float smoothingRadius;
const float targetDensity;
const float pressureMultiplier;
const float nearPressureMultiplier;
const float viscosityStrength;
const float edgeForce;
const float edgeForceDst;
const float3 boundsSize;
const float3 centre;
const int copyBufferId;		//Position = 0, PredictedPosition = 1, Velocity = 2, Density = 3
const int copyDirection;		//0 = real buffer to temp buffer, 1 = temp buffer to real buffer

const float4x4 localToWorld;
const float4x4 worldToLocal;

const float2 interactionInputPoint;
const float interactionInputStrength;
const float interactionInputRadius;

float PressureFromDensity(float density)
{
	return (density - targetDensity) * pressureMultiplier;
}

float NearPressureFromDensity(float nearDensity)
{
	return nearDensity * nearPressureMultiplier;
}

void ResolveCollisions(uint particleIndex)
{
	// Transform position/velocity to the local space of the bounding box (scale not included)
	float3 posLocal = mul(worldToLocal, float4(Positions[particleIndex], 1)).xyz;
	float3 velocityLocal = mul(worldToLocal, float4(Velocities[particleIndex], 0)).xyz;

	// Calculate distance from box on each axis (negative values are inside box)
	const float3 halfSize = 0.5;
	const float3 edgeDst = halfSize - abs(posLocal);

	// Resolve collisions
	if (edgeDst.x <= 0)
	{
		posLocal.x = halfSize.x * sign(posLocal.x);
		velocityLocal.x *= -1 * collisionDamping;
	}
	if (edgeDst.y <= 0)
	{
		posLocal.y = halfSize.y * sign(posLocal.y);
		velocityLocal.y *= -1 * collisionDamping;
	}
	if (edgeDst.z <= 0)
	{
		posLocal.z = halfSize.z * sign(posLocal.z);
		velocityLocal.z *= -1 * collisionDamping;
	}

	// Transform resolved position/velocity back to world space
	Positions[particleIndex] = mul(localToWorld, float4(posLocal, 1)).xyz;
	Velocities[particleIndex] = mul(localToWorld, float4(velocityLocal, 0)).xyz;

}

[numthreads(NUM_THREADS,1,1)]
void ExternalForces (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	// External forces (gravity)
	Velocities[id.x] += float3(0, gravity, 0) * deltaTime;

	// Predict
	PredictedPositions[id.x] = Positions[id.x] + Velocities[id.x] * 1 / 120.0;
}

[numthreads(NUM_THREADS,1,1)]
void InitializeSpacialPartitionBuffers (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	uint index = id.x;

	// Update index buffer
	int3 cell = GetCell3D(PredictedPositions[index], smoothingRadius);
	uint hash = HashCell3D(cell);
	uint key = KeyFromHash(hash, numParticles);

	spacialPart1[index] = key;
	spacialPart2[index] = index;
}

[numthreads(NUM_THREADS,1,1)]
void CalculateDensities (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;
	float density = 0;
	float nearDensity = 0;

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;
			
			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate density and near density
			float dst = sqrt(sqrDstToNeighbour);
			density += DensityKernel(dst, smoothingRadius);
			nearDensity += NearDensityKernel(dst, smoothingRadius);
		}
	}
	
	Densities[id.x] = float2(density, nearDensity);
}

[numthreads(NUM_THREADS,1,1)]
void CalculatePressureForce (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	// Calculate pressure
	float density = Densities[id.x][0];
	float densityNear = Densities[id.x][1];
	float pressure = PressureFromDensity(density);
	float nearPressure = NearPressureFromDensity(densityNear);
	float3 pressureForce = 0;
	
	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;

			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;
			// Skip if looking at self
			if (unincIndex == id.x) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate pressure force
			float densityNeighbour = Densities[unincIndex][0];
			float nearDensityNeighbour = Densities[unincIndex][1];
			float neighbourPressure = PressureFromDensity(densityNeighbour);
			float neighbourPressureNear = NearPressureFromDensity(nearDensityNeighbour);

			float sharedPressure = (pressure + neighbourPressure) / 2;
			float sharedNearPressure = (nearPressure + neighbourPressureNear) / 2;

			float dst = sqrt(sqrDstToNeighbour);
			float3 dir = dst > 0 ? offsetToNeighbour / dst : float3(0, 1, 0);

			pressureForce += dir * DensityDerivative(dst, smoothingRadius) * sharedPressure / densityNeighbour;
			pressureForce += dir * NearDensityDerivative(dst, smoothingRadius) * sharedNearPressure / nearDensityNeighbour;
		}
	}

	float3 acceleration = pressureForce / density;
	Velocities[id.x] += acceleration * deltaTime;
}


[numthreads(NUM_THREADS,1,1)]
void CalculateViscosity (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;
		
	float3 pos = PredictedPositions[id.x];
	int3 originCell = GetCell3D(pos, smoothingRadius);
	float sqrRadius = smoothingRadius * smoothingRadius;

	float3 viscosityForce = 0;
	float3 velocity = Velocities[id.x];

	// Neighbour search
	for (int i = 0; i < 27; i ++)
	{
		uint hash = HashCell3D(originCell + offsets3D[i]);
		uint key = KeyFromHash(hash, numParticles);
		int3 neighborCell;
		uint neighborHash;
		uint neighborKey;
		uint currIndex = spacialPart2[key];
		uint unincIndex;

		while (currIndex < numParticles)
		{
			unincIndex = currIndex;			
			currIndex ++;

			neighborKey = spacialPart1[unincIndex];
			// Exit if no longer looking at correct bin
			if (neighborKey != key) break;

			float3 neighbourPos = PredictedPositions[unincIndex];
			neighborCell = GetCell3D(neighbourPos, smoothingRadius);
			neighborHash = HashCell3D(neighborCell);

			// Skip if hash does not match
			if (neighborHash != hash) continue;
			// Skip if looking at self
			if (unincIndex == id.x) continue;

			float3 offsetToNeighbour = neighbourPos - pos;
			float sqrDstToNeighbour = dot(offsetToNeighbour, offsetToNeighbour);

			// Skip if not within radius
			if (sqrDstToNeighbour > sqrRadius) continue;

			// Calculate viscosity
			float dst = sqrt(sqrDstToNeighbour);
			float3 neighbourVelocity = Velocities[unincIndex];
			viscosityForce += (neighbourVelocity - velocity) * SmoothingKernelPoly6(dst, smoothingRadius);
		}
	}
	Velocities[id.x] += viscosityForce * viscosityStrength * deltaTime;
}

[numthreads(NUM_THREADS, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	Positions[id.x] += Velocities[id.x] * deltaTime;
	ResolveCollisions(id.x);
}

// The branchiness of this kernel is okay because all threads will follow the same branches on a given Dispatch so there will be no divergence
[numthreads(NUM_THREADS, 1, 1)]
void CopyBuffer(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) return;

	if (copyDirection == 0)
	{
		// Copy to temp buffer
		uint uncoalescedIndex = spacialPart2[id.x];
		if (copyBufferId == 0)
		{
			tempBuffer[id.x] = Positions[uncoalescedIndex];
		} 
		else if (copyBufferId == 1)
		{
			tempBuffer[id.x] = PredictedPositions[uncoalescedIndex];
		}
		else if (copyBufferId == 2)
		{
			tempBuffer[id.x] = Velocities[uncoalescedIndex];
		}
		else if (copyBufferId == 3)
		{
			float2 density = Densities[uncoalescedIndex];
			tempBuffer[id.x] = float3(density[0], density[1], 0.0);
		}
	}
	else
	{
		// Copy from temp buffer
		if (copyBufferId == 0)
		{
			Positions[id.x] = tempBuffer[id.x];
		} 
		else if (copyBufferId == 1)
		{
			PredictedPositions[id.x] = tempBuffer[id.x];
		}
		else if (copyBufferId == 2)
		{
			Velocities[id.x] = tempBuffer[id.x];
		}
		else if (copyBufferId == 3)
		{
			float3 density = tempBuffer[id.x];
			Densities[id.x] = float2(density[0], density[1]);
		}
	}
}

// Reinitialized the array formerly used to store scatter indices for sorting to be the key offset array.
// The values are all numParticles (which is 1 more than the maximum possible key) in order to ensure that
// any possible key is less than this value. This is important for determing the end of the key bucket
[numthreads(NUM_THREADS, 1, 1)]
void InitOffsets(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) { return; }

	spacialPart2[id.x] = numParticles;
}

// Calculate offsets into the sorted spacialPart1 buffer (used for spatial hashing).
// For example, given an spacialPart1 buffer sorted by key like so: {2, 2, 2, 3, 6, 6, 9, 9, 9, 9}
// The resulting Offsets (spacialPart2) calculated here should be:  {-, -, 0, 3, -, -, 4, -, -, 6}
// (where '-' represents elements that won't be read/written)
// 
// Usage example:
// Say we have a particular particle P, and we want to know which particles are in the same grid cell as it.
// First we would calculate the Key of P based on its position. Let's say in this example that Key = 9.
// Next we can look up spacialPart2[Key] to get: spacialPart2[9] = 6
// This tells us that SortedEntries[6] is the first particle that's in the same cell as P.
// We can then loop until we reach a particle with a different cell key in order to iterate over all the particles in the cell.
// 
// NOTE: offsets buffer must filled with values equal to (or greater than) its length to ensure that this works correctly
// So this depends on InitOffsets being run.
[numthreads(NUM_THREADS, 1, 1)]
void CalcOffsets(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numParticles) { return; }

	uint i = id.x;

	uint key = spacialPart1[i];
	uint keyPrev = i == 0 ? numParticles : spacialPart1[i - 1];

	if (key != keyPrev)
	{
		spacialPart2[key] = i;
	}
	
}



struct NeighborSearchIterationID
{
	uint key;				//Key of the neighbor cell
	uint particleTurn;		//warp-relative index of particle whose neighbors are being checked. [0-(NUM_THREADS-1)]
	uint neighborTurn;		//index into offsets3D of neighbor to be checked for particle. [0-26]
};

groupshared float3 sh_thisParticlePositions[NUM_THREADS];

//Initializes shared memory with this particle's position, then finds common neighbor cells among all threads in this warp
void initNeighborSearch(uint globalOffset, uint threadsPerWarp, uint thisParticleIndex, out NeighborSearchIterationID nsIterations[27])
{
	float3 thisParticlePosition = PredictedPositions[globalOffset + thisParticleIndex];
	sh_thisParticlePositions[thisParticleIndex] = thisParticlePosition;
	int3 thisParticleOriginCell = GetCell3D(thisParticlePosition, smoothingRadius);

	//Init NeighborSearchIterationIDs to all this thread's iterations. This assumes no commonality found by default.
	uint curNeighborHash;
	uint curNeighborKey;
	for (int curNeighborIndex = 0; curNeighborIndex < 27; curNeighborIndex++)
	{
		curNeighborHash = HashCell3D(thisParticleOriginCell + offsets3D[curNeighborIndex]);
		curNeighborKey = KeyFromHash(curNeighborHash, numParticles);

		nsIterations[curNeighborIndex].key = curNeighborKey;
		nsIterations[curNeighborIndex].particleTurn = thisParticleIndex;
		nsIterations[curNeighborIndex].neighborTurn = curNeighborIndex;
	}

	//Loop through all particles in warp and compute neighbor keys of each particle. If an earlier particle is searching the same
	//neighbor as this particle, then use that instead.
	uint neighborsCheckedByThisParticle = 27;

	float3 curParticlePosition;
	int3 curParticleOriginCell;
	bool curParticleEarlierThanThisParticle;
	uint shouldReplace;
	uint shouldNotReplace;
	for (uint curParticleIndex = 0; curParticleIndex < threadsPerWarp; curParticleIndex++)
	{
		curParticleEarlierThanThisParticle = curParticleIndex < thisParticleIndex;
		curParticlePosition = sh_thisParticlePositions[curParticleIndex];
		curParticleOriginCell = GetCell3D(curParticlePosition, smoothingRadius);

		for (uint curOtherParticleNeighborIndex = 0; curOtherParticleNeighborIndex < 27; curOtherParticleNeighborIndex++)
		{
			curNeighborHash = HashCell3D(curParticleOriginCell + offsets3D[curOtherParticleNeighborIndex]);
			curNeighborKey = KeyFromHash(curNeighborHash, numParticles);

			for (uint curThisParticleNeighborIndex = 0; curThisParticleNeighborIndex < 27; curThisParticleNeighborIndex++)
			{
				shouldReplace = (curNeighborKey == nsIterations[curThisParticleNeighborIndex].key)
					&& curParticleEarlierThanThisParticle;
				shouldNotReplace = (1 - shouldReplace);

				nsIterations[curThisParticleNeighborIndex].particleTurn *= shouldNotReplace;
				nsIterations[curThisParticleNeighborIndex].neighborTurn *= shouldNotReplace;
				nsIterations[curThisParticleNeighborIndex].particleTurn += shouldReplace * curParticleIndex;
				nsIterations[curThisParticleNeighborIndex].neighborTurn += shouldReplace * curOtherParticleNeighborIndex;

				neighborsCheckedByThisParticle -= shouldReplace;
			}
		}
	}

	//TODO calculate iterations per particle based on neighborsCheckedByThisParticle
}


[numthreads(NEIGHBOR_SEARCH_NUM_THREADS, 1, 1)]
void Debug(uint3 globalId : SV_DispatchThreadID, uint3 warpId : SV_GroupThreadID)
{
	if (globalId.x >= numParticles) { return; }
	bool conditionMet;

	NeighborSearchIterationID results[27];
	initNeighborSearch(globalId.x - warpId.x, NEIGHBOR_SEARCH_NUM_THREADS, warpId.x, results);

	bool atLeastOneShared = false;
	for (int i = 0; i < 27; i++)
	{
		atLeastOneShared = atLeastOneShared || (results[i].particleTurn != warpId.x);
	}

	conditionMet = atLeastOneShared;

	float testResultFloat = conditionMet * 6.0;
	DebugValues[globalId.x] = float3(testResultFloat, testResultFloat, testResultFloat);
}