#pragma kernel Sort

// Includes
#include "./GPUSortCommon.hlsl"

const uint groupWidth;
const uint groupHeight;
const uint stepIndex;

// Sort the given entries by their keys (smallest to largest)
// This is done using bitonic merge sort, and takes multiple iterations
[numthreads(128, 1, 1)]
void Sort (uint3 id : SV_DispatchThreadID)
{
	uint i = id.x;

	uint hIndex = i & (groupWidth - 1);
	uint indexLeft = hIndex + (groupHeight + 1) * (i / groupWidth);
	uint rightStepSize = stepIndex == 0 ? groupHeight - 2 * hIndex : (groupHeight + 1) / 2;
	uint indexRight = indexLeft + rightStepSize;

	// Exit if out of bounds (for non-power of 2 input sizes)
	if (indexRight >= numEntries) return;

	uint valueLeft = spacialPart1[indexLeft].x;
	uint valueRight = spacialPart1[indexRight].x;

	// Swap entries if value is descending
	uint2 tmp;
	if (valueLeft > valueRight)
	{
		tmp = spacialPart1[indexLeft];

		spacialPart1[indexLeft] = spacialPart1[indexRight];

		spacialPart1[indexRight] = tmp;
	}
}