#pragma kernel CopyVoxVols

#define NUM_THREADS							64

// =======================================
// Buffers
// =======================================

// Global voxel heap
RWStructuredBuffer<uint> VoxelBuffer;


// =======================================
// Constants
// =======================================

uint Src;
uint Dst;
uint Size;


// =======================================
// KERNELS
// =======================================

[numthreads(NUM_THREADS, 1, 1)]
void CopyVoxVols(uint3 id : SV_DispatchThreadID)
{
    uint globalIndex = id.x;

    if (globalIndex >= Size)
        return;

    VoxelBuffer[Dst + globalIndex] = VoxelBuffer[Src + globalIndex];
}